name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck
        working-directory: ./packages/qwik-solid
      - run: pnpm run lint
        working-directory: ./packages/qwik-solid
